# fly.toml app configuration file generated for chatbot1 on 2024-03-12T16:27:09+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chatbot1'
primary_region = 'nrt'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[[services]]
  protocol = 'tcp'
  internal_port = 8000

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20
	
  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']



[[vm]]
  size = 'shared-cpu-1x'
